path_dataSet_for_train: "../data/Titanic-Dataset.csv"
path_dataSet_for_test: "../data/tested.csv"

path_model_Performance_decision_tree_score: "../src/Model_Performance/decision_tree/scores/decision_tree_scores.txt"
path_model_Performance_decision_tree_plot: "../src/Model_Performance/decision_tree/plot/decision_tree_plot.png"

path_model_Performance_random_fores_score: "../src/Model_Performance/random_forest/scores/random_forest_scores.txt"
path_model_Performance_random_forest_plot: "../src/Model_Performance/random_forest/plot/random_forest_plot"

path_mis_classified_samples: "../src/Model_Performance/decision_tree/mis_classified_samples/mis_classified_samples"

decision_tree_parameters:
  max_depth: [3]
  min_samples_split: [2]
  min_samples_leaf: [3]

random_forest_parameters:
  n_estimators: [100]
  max_depth: [3]
  min_samples_split: [2]
  min_samples_leaf: [5]
  bootstrap: [True, False]


